### PR TITLE
[DO-1014] Use windows large runners and explicitly named self hosted linux runners

### PR DESCRIPTION
**Pull request by shambupujar**

### CODE REVIEW

**Comment by shambupujar** [comment]
Below is the comparision of the execution timings on different kind of runners. 
To summarize, 

- the k8s linux self hosted runners are faster than github ubuntu 16 core runners and 5 times cheaper. 
- The windows large size runners whether it is 32cores or 16 cores, job completion timings are nearly on same.  

 So the decision as of now is to go with k8s self hosted runners for linux and github hosted  16 core runner for windows

Windows 32 Cores and ubuntu 16 cores | Windows 16 cores and ubuntu 16 crores | Windows 16 cores and k8s self hosted  linux runner |
-- | -- | --
CI / Cancel running workflows (pull_request) Successful in 4s | CI / Cancel running workflows (pull_request) Successful in 4s | CI / Cancel running workflows (pull_request) Successful in 7s
CI / Check code format (ubuntu-latest-16-cores) (pull_request) Successful in 4m | CI / Check code format (ubuntu-latest-16-cores) (pull_request) Successful in 9m | CI / Check code format (k8s-linux-runner) (pull_request) Successful in 9m
CI / Run SBOR unit tests (ubuntu-latest-16-cores) (pull_request) Successful in 54s | CI / Run SBOR unit tests (ubuntu-latest-16-cores) (pull_request) Successful in 1m | CI / Run SBOR unit tests (k8s-linux-runner) (pull_request) Successful in 1m
CI / Run SBOR unit tests (windows-latest-32-cores) (pull_request) Successful in 3m | CI / Run SBOR unit tests (windows-latest-16-cores) (pull_request) Successful in 1m | CI / Run SBOR unit tests (windows-latest-16-cores) (pull_request) Successful in 1m
CI / Run SBOR integration tests (ubuntu-latest-16-cores) (pull_request) Successful in 1m | CI / Run SBOR integration tests (ubuntu-latest-16-cores) (pull_request) Successful in 1m | CI / Run SBOR integration tests (k8s-linux-runner) (pull_request) Successful in 1m
CI / Run SBOR integration tests (windows-latest-32-cores) (pull_request) Successful in 3m | CI / Run SBOR integration tests (windows-latest-16-cores) (pull_request) Successful in 1m | CI / Run SBOR integration tests (windows-latest-16-cores) (pull_request) Successful in 1m
CI / Run Scrypto unit tests (ubuntu-latest-16-cores) (pull_request) Successful in 1m | CI / Run Scrypto unit tests (ubuntu-latest-16-cores) (pull_request) Successful in 1m | CI / Run Scrypto unit tests (k8s-linux-runner) (pull_request) Successful in 1m
CI / Run Scrypto unit tests (windows-latest-32-cores) (pull_request) Successful in 4m | CI / Run Scrypto unit tests (windows-latest-16-cores) (pull_request) Successful in 1m | CI / Run Scrypto unit tests (windows-latest-16-cores) (pull_request) Successful in 1m
CI / Run Scrypto integration tests (ubuntu-latest-16-cores) (pull_request) Successful in 1m | CI / Run Scrypto integration tests (ubuntu-latest-16-cores) (pull_request) Successful in 1m | CI / Run Scrypto integration tests (k8s-linux-runner) (pull_request) Successful in 1m
CI / Run Scrypto integration tests (windows-latest-32-cores) (pull_request) Successful in 3m | CI / Run Scrypto integration tests (windows-latest-16-cores) (pull_request) Successful in 1m | CI / Run Scrypto integration tests (windows-latest-16-cores) (pull_request) Successful in 1m
CI / Run Scrypto examples (ubuntu-latest-16-cores) (pull_request) Successful in 6m | CI / Run Scrypto examples (ubuntu-latest-16-cores) (pull_request) Successful in 3m | CI / Run Scrypto examples (k8s-linux-runner) (pull_request) Successful in 3m
CI / Run Scrypto examples (windows-latest-32-cores) (pull_request) Successful in 15m | CI / Run Scrypto examples (windows-latest-16-cores) (pull_request) Successful in 3m | CI / Run Scrypto examples (windows-latest-16-cores) (pull_request) Successful in 2m
CI / Run Radix Engine tests (ubuntu-latest-16-cores) (pull_request) Successful in 9m | CI / Run Radix Engine tests (ubuntu-latest-16-cores) (pull_request) Successful in 9m | CI / Run Radix Engine tests (k8s-linux-runner) (pull_request) Successful in 8m
CI / Run Radix Engine tests (no_std) (ubuntu-latest-16-cores) (pull_request) Successful in 8m | CI / Run Radix Engine tests (no_std) (ubuntu-latest-16-cores) (pull_request) Successful in 7m | CI / Run Radix Engine tests (no_std) (k8s-linux-runner) (pull_request) Successful in 5m
CI / Run Radix Engine tests with Wasmer (ubuntu-latest-16-cores) (pull_request) Successful in 10m | CI / Run Radix Engine tests with Wasmer (ubuntu-latest-16-cores) (pull_request) Successful in 9m | CI / Run Radix Engine tests with Wasmer (k8s-linux-runner) (pull_request) Successful in 8m
CI / Run Radix Engine benchmarks (ubuntu-latest-16-cores) (pull_request) Successful in 4m | CI / Run Radix Engine benchmarks (ubuntu-latest-16-cores) (pull_request) Successful in 3m | CI / Run Radix Engine benchmarks (k8s-linux-runner) (pull_request) Successful in 3m
CI / Run transaction tests (ubuntu-latest-16-cores) (pull_request) Successful in 2m | CI / Run transaction tests (ubuntu-latest-16-cores) (pull_request) Successful in 1m | CI / Run transaction tests (k8s-linux-runner) (pull_request) Successful in 1m
CI / Run transaction tests (windows-latest-32-cores) (pull_request) Successful in 3m | CI / Run transaction tests (windows-latest-16-cores) (pull_request) Successful in 1m | CI / Run transaction tests (windows-latest-16-cores) (pull_request) Successful in 1m
CI / Run CLI tests (ubuntu-latest-16-cores) (pull_request) Successful in 16m | CI / Run CLI tests (ubuntu-latest-16-cores) (pull_request) Successful in 12m | CI / Run CLI tests (k8s-linux-runner) (pull_request) Successful in 9m
CI / Run CLI tests (windows-latest-32-cores) (pull_request) Successful in 11m | CI / Run CLI tests (windows-latest-16-cores) (pull_request) Successful in 13m | CI / Run CLI tests (windows-latest-16-cores) (pull_request) Successful in 10m
CI / Run CLI tests - part 2 (ubuntu-latest-16-cores) (pull_request) Successful in 15m | CI / Run CLI tests - part 2 (ubuntu-latest-16-cores) (pull_request) Successful in 11m | CI / Run CLI tests - part 2 (k8s-linux-runner) (pull_request) Successful in 3m
CI / Run CLI tests - part 2 (windows-latest-32-cores) (pull_request) Successful in 15m | CI / Run CLI tests - part 2 (windows-latest-16-cores) (pull_request) Successful in 10m | CI / Run CLI tests - part 2 (windows-latest-16-cores) (pull_request) Successful in 12m

**Comment by iamyulong** [comment]
This is very nice! Thanks a lot @shambupujar!

**Review by iamyulong — APPROVED** [review]

**Comment by dhedey** [comment]
Sound great, thanks @shambupujar !

There's so much variety in the windows build times - eg this line:

CI / Run Scrypto examples (windows-latest-32-cores) (pull_request) Successful in 15m | CI / Run Scrypto examples (windows-latest-16-cores) (pull_request) Successful in 3m | CI / Run Scrypto examples (windows-latest-16-cores) (pull_request) Successful in 2m
-- | -- | --

Which I notice a lot in practice - do you have any ideas what might cause this?

Are these runners github runners rather than our runners? I take it we can't easily run our own windows runners? (because we can't stick them in kubernetes :') )

**Comment by shambupujar** [comment]
> 

Yeah windows ones are github hosted runners.  Whether runners are from github or self hosted, there is some time spent waiting for runners to be ready as they are ephemeral.  So the time difference you seeing could be due to that .

**Pull request merged**
