### PR TITLE
`CALL_METHOD_WITH_ALL_RESOURCES` instruction refactor

### PR DESCRIPTION
**Pull request by 0xOmarA**
This PR refactors the logic behind the `CALL_METHOD_WITH_ALL_RESOURCES` instruction so that the instruction no longer drops all proofs when called. Instead, if the caller wishes to drop all proofs, they can do that with the newly added `DROP_ALL_PROOFS` instruction. 

In summary, currently, the `CALL_METHOD_WITH_ALL_RESOURCES` instruction does the following:
1. Clears the AuthZone
2. Drops all proofs in the transaction
3. Collects all buckets to use for a method call.

This PR changes it so that 1 and 2 are done by a `DROP_ALL_PROOFS` instruction and 3 is done by the `CALL_METHOD_WITH_ALL_RESOURCES` instruction,

This is in relation to issue #367.

### CODE REVIEW

**Comment by iamyulong** [comment]
Looks good to me. The only question I have is if we should rename `CALL_METHOD_WITH_ALL_RESOURCES ` to `CALL_METHOD_WITH_ALL_WORKTOP_RESOURCES` to reflect on the fact that buckets taken from worktop are not included?

**Review by iamyulong — APPROVED** [review]

**Comment by 0xOmarA** [comment]
@iamyulong Both names are okay with me, should we add this as an item to the to discuss list for tomorrow's call?

**Comment by iamyulong** [comment]
Let's add it to the to discuss list. You can merge this PR if want. No need to wait for that.

**Comment by 0xOmarA** [comment]
@iamyulong Sounds good, will resolve the merge conflicts and go ahead and merge :)

**Pull request merged**
