### PR TITLE
The square root of a Decimal.

### PR DESCRIPTION
**Pull request by a137x**
The square root of a Decimal. Uses a standard Babylonian method.

### CODE REVIEW

**Comment by a137x** [comment]
Referring to [this](https://docs.rs/rust_decimal/latest/src/rust_decimal/maths.rs.html#328) implementation.

**Comment by 0xOmarA** [comment]
Hey @a137x, thank you for this PR! Do you mind changing the base branch to be the `develop` branch?

**Comment by a137x** [comment]
Pardon, misclicked.
@0xOmarA 
base "develop" - done.

**Comment by a137x** [comment]
Apologies. Closing this request to open new one. Messed up with branches, committed to main which is far behind develop.

**Pull request closed without merging**
